### ISSUE TITLE
Support kitty cli graphics protocol

### ISSUE THREAD

**Issue by forivall** [sindresorhus/term-img#15]
Protocol definition: https://sw.kovidgoyal.net/kitty/graphics-protocol.html
Reference code: https://github.com/kovidgoyal/kitty/blob/main/kittens/icat/main.py

Some reading that someone with more : https://github.com/weechat/weechat/issues/1430

According to the protocol document, xterm also supports this graphics protocol, although, i haven't tested it.

**Comment by tmgldn** [comment]
I'm interested in fixing this.

To do this I'd create a library that matches this ones api, and add a PR for the [terminal-image](https://github.com/sindresorhus/terminal-image) repo - does that sound okay @sindresorhus ?

**Comment by sindresorhus** [comment]
> does that sound okay @sindresorhus ?

👍

**Comment by tmgldn** [comment]
@sindresorhus @forivall

So, I've created this library: [`npm:term-kitty-img`](https://github.com/tbjgolden/term-kitty-img) to allow people to use the kitty protocol from node.

However, it's not easily compatible with this library (would likely need a new major version).

This is because to check if the kitty terminal supports images (which it doesn't inside some programs like termux) you're required to wait for a response. While `term-img` is synchronous, a solution for kitty would need to be asynchronous, like `term-kitty-img`.

**Comment by sindresorhus** [comment]
I think for now it would be best to just link to your package from the readme. I don't want to make this package async.
